# Generated by Django 5.2.6 on 2026-06-21 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0003_knowledgedocument_tenant'),
        ('tenants', '0004_membership_role_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField(verbose_name='分块序号')),
                ('content', models.TextField(verbose_name='分块内容')),
                ('content_hash', models.CharField(max_length=64, verbose_name='内容哈希')),
                ('embedding', models.JSONField(blank=True, default=list, verbose_name='向量')),
                ('embedding_model', models.CharField(max_length=128, verbose_name='嵌入模型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge_base.knowledgedocument', verbose_name='所属知识库文档')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '知识库文档分块',
                'verbose_name_plural': '知识库文档分块',
                'ordering': ['document_id', 'chunk_index'],
                'indexes': [models.Index(fields=['tenant', 'document'], name='knowledge_b_tenant__c5ec05_idx'), models.Index(fields=['document', 'embedding_model'], name='knowledge_b_documen_225cd9_idx')],
                'constraints': [models.UniqueConstraint(fields=('document', 'embedding_model', 'chunk_index'), name='uniq_knowledge_chunk_document_model_index')],
            },
        ),
    ]
