# Generated by Codex on 2026-06-25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('knowledge_base', '0008_remove_knowledge_document_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedocument',
            name='chunk_count',
            field=models.PositiveIntegerField(default=0, verbose_name='分块数量'),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='index_error',
            field=models.TextField(blank=True, default='', verbose_name='索引错误'),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='index_model',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='索引模型'),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='index_status',
            field=models.CharField(
                choices=[
                    ('pending', '待索引'),
                    ('indexing', '索引中'),
                    ('ready', '已就绪'),
                    ('failed', '索引失败'),
                ],
                default='pending',
                max_length=16,
                verbose_name='索引状态',
            ),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='indexed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='索引完成时间'),
        ),
    ]
