# Generated by Django 5.2.6 on 2026-07-20 07:25

import apps.app_updates.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0023_deviceauthorizationcode_application_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_id', models.CharField(default=apps.app_updates.models.generate_release_id, editable=False, max_length=64, unique=True, verbose_name='发布 ID')),
                ('package_name', models.CharField(default='com.solin.digital', max_length=255, verbose_name='应用包名')),
                ('version_name', models.CharField(max_length=64, verbose_name='版本名称')),
                ('version_code', models.PositiveBigIntegerField(unique=True, verbose_name='内部版本号')),
                ('version_info', models.CharField(max_length=255, unique=True, verbose_name='完整版本标识')),
                ('apk_file', models.FileField(max_length=512, upload_to=apps.app_updates.models.app_release_upload_to, verbose_name='APK 文件')),
                ('file_name', models.CharField(editable=False, max_length=255, verbose_name='原始文件名')),
                ('file_size', models.PositiveBigIntegerField(editable=False, verbose_name='文件大小')),
                ('sha256', models.CharField(editable=False, max_length=64, verbose_name='SHA-256')),
                ('force_upgrade_version_code', models.PositiveBigIntegerField(default=0, verbose_name='强制升级阈值')),
                ('release_notes', models.TextField(blank=True, default='', verbose_name='更新说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_app_releases', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '应用发布版本',
                'verbose_name_plural': '应用发布版本',
                'ordering': ['-version_code', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AppUpdateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=255, verbose_name='应用包名')),
                ('current_version_code', models.PositiveBigIntegerField(verbose_name='更新前版本号')),
                ('target_version_code', models.PositiveBigIntegerField(verbose_name='目标版本号')),
                ('state', models.CharField(choices=[('UPDATE_AVAILABLE', '发现新版本'), ('DOWNLOADING', '开始下载'), ('DOWNLOADED', '下载完成'), ('VERIFIED', '校验成功'), ('READY_TO_INSTALL', '等待安装'), ('INSTALLING', '提交安装'), ('INSTALLED', '安装成功'), ('FAILED', '失败')], max_length=32, verbose_name='状态')),
                ('message', models.TextField(blank=True, default='', verbose_name='补充信息')),
                ('occurred_at', models.DateTimeField(verbose_name='客户端发生时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='接收时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='app_update_events', to='devices.device')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='app_updates.apprelease')),
            ],
            options={
                'verbose_name': '应用升级事件',
                'verbose_name_plural': '应用升级事件',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='apprelease',
            constraint=models.CheckConstraint(condition=models.Q(('version_code__gt', 0)), name='app_release_version_code_positive'),
        ),
        migrations.AddConstraint(
            model_name='apprelease',
            constraint=models.CheckConstraint(condition=models.Q(('force_upgrade_version_code__lte', models.F('version_code'))), name='app_release_force_threshold_lte_version'),
        ),
    ]
