# Generated by Django 5.2.6 on 2026-05-07 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_examples', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointapitest',
            options={'default_permissions': (), 'verbose_name': '指令任务接口测试', 'verbose_name_plural': '指令任务接口测试'},
        ),
    ]
