# Generated by Django 5.2.6 on 2026-06-01 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_backfill_business_tenants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_username', models.CharField(blank=True, max_length=150, verbose_name='操作人用户名')),
                ('action', models.CharField(choices=[('create', '新增'), ('update', '修改'), ('delete', '删除')], max_length=16, verbose_name='操作类型')),
                ('method', models.CharField(max_length=8, verbose_name='请求方法')),
                ('path', models.CharField(max_length=512, verbose_name='请求路径')),
                ('status_code', models.IntegerField(verbose_name='响应状态码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenants.tenant', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
