# Generated by Django 5.2.6 on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationlog',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='操作说明'),
        ),
    ]
