# Generated by Django 5.2.6 on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_operationlog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationlog',
            name='actor_role_name',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='操作人角色'),
        ),
    ]
