# Generated by Django 5.2.6 on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_operationlog_actor_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationlog',
            name='actor_display_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='操作人姓名'),
        ),
    ]
