# Generated by Django 5.2.6 on 2026-06-05

from django.db import migrations


def fix_existing_audit_logs(apps, schema_editor):
    OperationLog = apps.get_model('audit', 'OperationLog')

    OperationLog.objects.filter(actor__is_superuser=True, tenant__isnull=False).update(tenant=None)

    for log in OperationLog.objects.filter(
        path__regex=r'^/api/v1/knowledge-base/[0-9]+/review/?$',
        description__startswith='新增知识库文档',
    ).only('id', 'description'):
        suffix = log.description.removeprefix('新增知识库文档')
        log.description = f'审核知识库文档{suffix}'[:255]
        log.save(update_fields=['description'])


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_operationlog_actor_display_name'),
    ]

    operations = [
        migrations.RunPython(fix_existing_audit_logs, migrations.RunPython.noop),
    ]
