# Generated by Claude Code on 2026-04-11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_role_menu_permissionpoint_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.menu', verbose_name='父级菜单'),
        ),
    ]
