# Generated by Django 5.2.6 on 2026-05-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_menu_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountapplication',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='登录用户名'),
        ),
    ]
