# Generated by Django 5.2.6 on 2026-05-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_accountapplication_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountapplication',
            name='email',
        ),
        migrations.AddField(
            model_name='accountapplication',
            name='enterprise_name',
            field=models.CharField(default='', max_length=128, verbose_name='企业名称'),
        ),
        migrations.AddField(
            model_name='accountapplication',
            name='password',
            field=models.CharField(default='', max_length=128, verbose_name='登录密码哈希'),
        ),
    ]
