# Generated by Django 5.2.6 on 2026-05-31 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_accountuser'),
        ('tenants', '0003_backfill_business_tenants'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountapplication',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenants.tenant', verbose_name='开通公司'),
        ),
    ]
