# Generated by Django 5.2.6 on 2026-05-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_accountapplication_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='audience',
            field=models.CharField(choices=[('all', '通用业务菜单（可分配）'), ('platform', '平台超管专属'), ('tenant_admin', '公司管理员专属')], default='all', max_length=20, verbose_name='菜单受众'),
        ),
    ]
