# Generated by Django 5.2.6 on 2026-05-31 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_seed_tenant_menus'),
        ('tenants', '0003_backfill_business_tenants'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_template',
            field=models.BooleanField(default=False, verbose_name='平台模板'),
        ),
        migrations.AddField(
            model_name='role',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='tenants.tenant', verbose_name='所属公司'),
        ),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(max_length=64, verbose_name='角色编码'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_role_code_per_tenant'),
        ),
    ]
