# Generated by Django 5.2.6 on 2026-04-09 03:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='设备编号')),
                ('name', models.CharField(max_length=128, verbose_name='设备名称')),
                ('location', models.CharField(max_length=128, verbose_name='部署位置')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('maintaining', '维护中')], default='offline', max_length=20, verbose_name='运行状态')),
                ('last_heartbeat', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最近心跳')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'ordering': ['code'],
            },
        ),
    ]
