# Generated by Django 5.2.6 on 2026-05-31 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('tenants', '0002_default_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='所属公司'),
        ),
        migrations.AlterField(
            model_name='device',
            name='code',
            field=models.CharField(max_length=32, verbose_name='设备编号'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_device_code_per_tenant'),
        ),
    ]
