# Generated by Django 5.2.6 on 2026-06-02 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_tenant_alter_device_code_and_more'),
        ('resources', '0028_commandgroup_tenant_controlcommand_tenant_and_more'),
        ('tenants', '0003_backfill_business_tenants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='authorization_type',
            field=models.CharField(choices=[('permanent', '永久'), ('trial', '试用')], default='permanent', max_length=20, verbose_name='授权类型'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_info',
            field=models.JSONField(blank=True, default=dict, verbose_name='设备信息'),
        ),
        migrations.AddField(
            model_name='device',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='到期时间'),
        ),
        migrations.AddField(
            model_name='device',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='device',
            name='last_auth_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后认证时间'),
        ),
        migrations.AddField(
            model_name='device',
            name='mainboard_info',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='主板信息'),
        ),
        migrations.AddField(
            model_name='device',
            name='registered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='注册时间'),
        ),
        migrations.AddField(
            model_name='device',
            name='software_version',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='软件版本'),
        ),
        migrations.AddField(
            model_name='device',
            name='system_version',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='系统版本'),
        ),
        migrations.AlterField(
            model_name='device',
            name='code',
            field=models.CharField(max_length=128, verbose_name='设备码'),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近心跳'),
        ),
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='部署位置'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('maintaining', '维护中')], default='offline', max_length=20, verbose_name='设备状态'),
        ),
        migrations.CreateModel(
            name='DeviceApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='应用名称')),
                ('code', models.SlugField(max_length=64, verbose_name='应用标识')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='应用说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('command_groups', models.ManyToManyField(blank=True, related_name='device_applications', to='resources.commandgroup', verbose_name='指令分组')),
                ('model_assets', models.ManyToManyField(blank=True, related_name='device_applications', to='resources.modelasset', verbose_name='模型')),
                ('resources', models.ManyToManyField(blank=True, related_name='device_applications', to='resources.resource', verbose_name='图片/视频资源')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='所属公司')),
                ('voice_tones', models.ManyToManyField(blank=True, related_name='device_applications', to='resources.voicetone', verbose_name='音色')),
            ],
            options={
                'verbose_name': '设备应用',
                'verbose_name_plural': '设备应用',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='devices.deviceapplication', verbose_name='绑定应用'),
        ),
        migrations.CreateModel(
            name='DeviceAuthorizationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='授权码')),
                ('status', models.CharField(choices=[('unused', '未使用'), ('used', '已使用'), ('disabled', '已禁用')], default='unused', max_length=20, verbose_name='状态')),
                ('authorization_type', models.CharField(choices=[('permanent', '永久'), ('trial', '试用')], default='trial', max_length=20, verbose_name='授权类型')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='到期时间')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorization_codes', to='devices.deviceapplication', verbose_name='绑定应用')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='所属公司')),
                ('used_by_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorization_codes', to='devices.device', verbose_name='使用设备')),
            ],
            options={
                'verbose_name': '设备授权码',
                'verbose_name_plural': '设备授权码',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DeviceAuthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=128, verbose_name='设备码')),
                ('action', models.CharField(choices=[('activate', '激活'), ('heartbeat', '心跳'), ('config', '配置拉取')], max_length=32, verbose_name='动作')),
                ('result', models.BooleanField(default=False, verbose_name='结果')),
                ('message', models.CharField(blank=True, default='', max_length=255, verbose_name='消息')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('device_info', models.JSONField(blank=True, default=dict, verbose_name='设备信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='devices.deviceapplication')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_logs', to='devices.device')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('auth_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_logs', to='devices.deviceauthorizationcode')),
            ],
            options={
                'verbose_name': '设备授权日志',
                'verbose_name_plural': '设备授权日志',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='分组名称')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '设备分组',
                'verbose_name_plural': '设备分组',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='devices.devicegroup', verbose_name='设备分组'),
        ),
        migrations.AddConstraint(
            model_name='deviceapplication',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_device_application_code_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='devicegroup',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_device_group_name_per_tenant'),
        ),
    ]
