# Generated by Codex on 2026-06-02

from django.db import migrations, models


def normalize_legacy_statuses(apps, schema_editor):
    Device = apps.get_model('devices', 'Device')
    Device.objects.filter(status='maintaining').update(status='offline')


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_authorization_type_device_device_info_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_legacy_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(
                choices=[('online', '在线'), ('offline', '离线')],
                default='offline',
                max_length=20,
                verbose_name='设备状态',
            ),
        ),
    ]
