# Generated by Codex on 2026-06-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_device_status_online_offline_only'),
        ('resources', '0028_commandgroup_tenant_controlcommand_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceapplication',
            name='scrolling_texts',
            field=models.ManyToManyField(
                blank=True,
                related_name='device_applications',
                to='resources.scrollingtext',
                verbose_name='滚动文本',
            ),
        ),
    ]
