# Generated by Hermes Agent

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0023_llmmodel_enable_web_search'),
        ('devices', '0006_device_authorization_ignored_at_and_log_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='agent_application',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='bound_devices',
                to='ai_models.agentapplication',
                verbose_name='绑定智能体',
            ),
        ),
        migrations.AlterField(
            model_name='device',
            name='application',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='devices',
                to='devices.deviceapplication',
                verbose_name='绑定资源应用',
            ),
        ),
    ]
