# Generated by Django 5.2.6 on 2026-06-19 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0023_llmmodel_enable_web_search'),
        ('devices', '0007_device_agent_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceauthlog',
            name='agent_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ai_models.agentapplication', verbose_name='绑定智能体快照'),
        ),
    ]
