# Generated by Codex on 2026-07-04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0015_drop_legacy_devicechatlog_third_party_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='WakeWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=16, verbose_name='唤醒词')),
                ('encoded_text', models.CharField(max_length=255, verbose_name='编码后唤醒词')),
                ('boost', models.DecimalField(decimal_places=2, default=2.0, max_digits=4, verbose_name='增强分数')),
                ('threshold', models.DecimalField(decimal_places=2, default=0.25, max_digits=4, verbose_name='触发阈值')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('devices', models.ManyToManyField(blank=True, related_name='wake_words', to='devices.device', verbose_name='绑定设备')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '唤醒词',
                'verbose_name_plural': '唤醒词',
                'ordering': ['text', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='wakeword',
            constraint=models.UniqueConstraint(fields=('tenant', 'text'), name='unique_wake_word_text_per_tenant'),
        ),
    ]
