# Generated by Django 5.2.6 on 2026-07-06 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0016_wakeword'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wakeword',
            name='unique_wake_word_text_per_tenant',
        ),
    ]
