# Generated by Django 5.2.6 on 2026-07-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0020_devicechatlog_runtime_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_software_trial',
            field=models.BooleanField(default=False, verbose_name='是否软件试用'),
        ),
    ]
