# Generated by Django 5.2.6 on 2026-07-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0023_deviceauthorizationcode_application_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicechatlog',
            name='knowledge_references',
            field=models.JSONField(blank=True, default=list, verbose_name='知识引用快照'),
        ),
    ]
