# Generated by Django 5.2.6 on 2026-05-31 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_accountuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='公司名称')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='公司标识')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_legacy', models.BooleanField(default=False, verbose_name='历史默认公司')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('menus', models.ManyToManyField(blank=True, related_name='tenants', to='accounts.menu', verbose_name='可见菜单')),
                ('permission_points', models.ManyToManyField(blank=True, related_name='tenants', to='accounts.permissionpoint', verbose_name='可用权限点')),
            ],
            options={
                'verbose_name': '公司',
                'verbose_name_plural': '公司',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_tenant_admin', models.BooleanField(default=False, verbose_name='公司管理员')),
                ('must_change_password', models.BooleanField(default=False, verbose_name='需强制改密')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.tenant', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '公司成员',
                'verbose_name_plural': '公司成员',
                'ordering': ['tenant_id', 'user_id'],
            },
        ),
    ]
