# Generated by Codex on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_backfill_business_tenants'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='role_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='角色名称'),
        ),
    ]
