# Generated by Claude Code on 2026-04-11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='资源名称')),
                ('resource_type', models.CharField(choices=[('image', '背景图片'), ('video', '视频')], max_length=20, verbose_name='资源类型')),
                ('category', models.CharField(choices=[('horizontal', '横屏'), ('vertical', '竖屏'), ('uncategorized', '未分类')], default='uncategorized', max_length=20, verbose_name='资源分类')),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/%Y/%m/%d', verbose_name='资源文件')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='资源说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '资源',
                'verbose_name_plural': '资源',
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
