# Generated by Claude Code on 2026-04-11

from django.db import migrations


def seed_resource_access_data(apps, schema_editor):
    Menu = apps.get_model('accounts', 'Menu')
    PermissionPoint = apps.get_model('accounts', 'PermissionPoint')

    resource_parent, _ = Menu.objects.update_or_create(
        key='/resources',
        defaults={
            'name': '资源管理',
            'path': '/resources',
            'icon': 'PictureOutlined',
            'sort_order': 30,
            'is_active': True,
            'parent_id': None,
        },
    )

    menus = [
        {
            'name': '背景图片管理',
            'key': '/resources/images',
            'path': '/resources/images',
            'icon': 'PictureOutlined',
            'sort_order': 31,
            'is_active': True,
            'parent_id': resource_parent.id,
        },
        {
            'name': '视频管理',
            'key': '/resources/videos',
            'path': '/resources/videos',
            'icon': 'VideoCameraOutlined',
            'sort_order': 32,
            'is_active': True,
            'parent_id': resource_parent.id,
        },
    ]

    for item in menus:
        Menu.objects.update_or_create(key=item['key'], defaults=item)

    permission_points = [
        ('查看背景图片', 'resources.images.view', 'resources_images', '允许查看背景图片资源'),
        ('创建背景图片', 'resources.images.create', 'resources_images', '允许创建背景图片资源'),
        ('编辑背景图片', 'resources.images.update', 'resources_images', '允许编辑背景图片资源'),
        ('删除背景图片', 'resources.images.delete', 'resources_images', '允许删除背景图片资源'),
        ('查看视频', 'resources.videos.view', 'resources_videos', '允许查看视频资源'),
        ('创建视频', 'resources.videos.create', 'resources_videos', '允许创建视频资源'),
        ('编辑视频', 'resources.videos.update', 'resources_videos', '允许编辑视频资源'),
        ('删除视频', 'resources.videos.delete', 'resources_videos', '允许删除视频资源'),
    ]

    for name, code, module, description in permission_points:
        PermissionPoint.objects.update_or_create(
            code=code,
            defaults={
                'name': name,
                'module': module,
                'description': description,
                'is_active': True,
            },
        )


def unseed_resource_access_data(apps, schema_editor):
    Menu = apps.get_model('accounts', 'Menu')
    PermissionPoint = apps.get_model('accounts', 'PermissionPoint')

    PermissionPoint.objects.filter(code__startswith='resources.').delete()
    Menu.objects.filter(key__in=['/resources/images', '/resources/videos', '/resources']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_menu_parent'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_resource_access_data, unseed_resource_access_data),
    ]
