# Generated by Codex on 2026-04-13

from django.db import migrations, models


def seed_voice_tone_access_data(apps, schema_editor):
    Menu = apps.get_model('accounts', 'Menu')
    PermissionPoint = apps.get_model('accounts', 'PermissionPoint')
    Role = apps.get_model('accounts', 'Role')

    resource_parent = Menu.objects.filter(key='/resources').first()
    if resource_parent is None:
        resource_parent, _ = Menu.objects.update_or_create(
            key='/resources',
            defaults={
                'name': '资源管理',
                'path': '/resources',
                'icon': 'PictureOutlined',
                'sort_order': 30,
                'is_active': True,
                'parent_id': None,
            },
        )

    voice_tone_menu, _ = Menu.objects.update_or_create(
        key='/resources/voice-tones',
        defaults={
            'name': '音色管理',
            'path': '/resources/voice-tones',
            'icon': 'CustomerServiceOutlined',
            'sort_order': 33,
            'is_active': True,
            'parent_id': resource_parent.id,
        },
    )

    permission_points = [
        ('查看音色', 'resources.voice_tones.view', 'resources_voice_tones', '允许查看音色资源'),
        ('创建音色', 'resources.voice_tones.create', 'resources_voice_tones', '允许创建音色资源'),
        ('编辑音色', 'resources.voice_tones.update', 'resources_voice_tones', '允许编辑音色资源'),
        ('删除音色', 'resources.voice_tones.delete', 'resources_voice_tones', '允许删除音色资源'),
    ]

    created_permission_points = []

    for name, code, module, description in permission_points:
        permission_point, _ = PermissionPoint.objects.update_or_create(
            code=code,
            defaults={
                'name': name,
                'module': module,
                'description': description,
                'is_active': True,
            },
        )
        created_permission_points.append(permission_point)

    for role in Role.objects.all():
        role.menus.add(voice_tone_menu)
        role.permission_points.add(*created_permission_points)


def unseed_voice_tone_access_data(apps, schema_editor):
    Menu = apps.get_model('accounts', 'Menu')
    PermissionPoint = apps.get_model('accounts', 'PermissionPoint')

    PermissionPoint.objects.filter(code__startswith='resources.voice_tones.').delete()
    Menu.objects.filter(key='/resources/voice-tones').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_menu_parent'),
        ('resources', '0002_seed_access_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceTone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='音色名称')),
                ('nickname', models.CharField(max_length=128, verbose_name='音色昵称')),
                ('voice_code', models.CharField(max_length=128, unique=True, verbose_name='音色标识')),
                ('content', models.TextField(blank=True, default='', verbose_name='音色内容')),
                ('icon', models.FileField(blank=True, null=True, upload_to='voice-tones/%Y/%m/%d', verbose_name='音色图标')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '音色',
                'verbose_name_plural': '音色',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.RunPython(seed_voice_tone_access_data, unseed_voice_tone_access_data),
    ]
