# Generated by Codex on 2026-04-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_voicetone_and_access_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voicetone',
            name='nickname',
        ),
        migrations.RenameField(
            model_name='voicetone',
            old_name='icon',
            new_name='audio',
        ),
        migrations.AlterField(
            model_name='voicetone',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='voice-tones/%Y/%m/%d', verbose_name='音色文件'),
        ),
    ]
