# Generated by Claude Code on 2026-04-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_voicetone_remove_nickname_add_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicetone',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='voice-tones/icons/%Y/%m/%d', verbose_name='音色图标'),
        ),
        migrations.AddField(
            model_name='voicetone',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='前端可见'),
        ),
        migrations.AlterField(
            model_name='voicetone',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='ASR结果'),
        ),
    ]
