# Generated by Django 5.2.6 on 2026-05-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0021_taskcommandstep_image_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlcommand',
            name='command_value_type',
            field=models.CharField(
                choices=[('string', '字符串'), ('hex', '16进制')],
                default='string',
                max_length=16,
                verbose_name='指令类型',
            ),
        ),
    ]
