# Generated by Codex on 2026-05-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0022_control_command_value_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlcommand',
            name='command_value_type',
            field=models.CharField(
                choices=[('string', '字符串'), ('hex', '16进制'), ('ascii', 'ascii')],
                default='string',
                max_length=16,
                verbose_name='指令类型',
            ),
        ),
    ]
