# Generated by Django 5.2.6 on 2026-05-31 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0027_point_is_show'),
        ('tenants', '0002_default_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandgroup',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='controlcommand',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='modelasset',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='point',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='resource',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='scrollingtext',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='taskcommand',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='voicetone',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='所属公司'),
        ),
        migrations.AlterField(
            model_name='controlcommand',
            name='command_code',
            field=models.CharField(max_length=128, verbose_name='指令'),
        ),
        migrations.AlterField(
            model_name='modelasset',
            name='name',
            field=models.CharField(max_length=128, verbose_name='模型名称'),
        ),
        migrations.AlterField(
            model_name='point',
            name='command',
            field=models.CharField(max_length=128, verbose_name='点位命令'),
        ),
        migrations.AlterField(
            model_name='taskcommand',
            name='command_code',
            field=models.CharField(max_length=128, verbose_name='指令'),
        ),
        migrations.AlterField(
            model_name='voicetone',
            name='voice_code',
            field=models.CharField(max_length=128, verbose_name='音色标识'),
        ),
        migrations.AddConstraint(
            model_name='controlcommand',
            constraint=models.UniqueConstraint(fields=('tenant', 'command_code'), name='unique_control_command_code_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='modelasset',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_model_asset_name_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='point',
            constraint=models.UniqueConstraint(fields=('tenant', 'command'), name='unique_point_command_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='taskcommand',
            constraint=models.UniqueConstraint(fields=('tenant', 'command_code'), name='unique_task_command_code_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='voicetone',
            constraint=models.UniqueConstraint(fields=('tenant', 'voice_code'), name='unique_voice_code_per_tenant'),
        ),
    ]
