# Generated by Django 5.2.6 on 2026-06-04 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0029_minio_config_and_resource_object_key'),
        ('tenants', '0003_backfill_business_tenants'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='object_size',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='MinIO 对象大小'),
        ),
        migrations.CreateModel(
            name='TenantVideoQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_mb', models.PositiveIntegerField(blank=True, null=True, verbose_name='视频容量额度（MB）')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_quota', to='tenants.tenant')),
            ],
            options={
                'verbose_name': '公司视频额度',
                'verbose_name_plural': '公司视频额度',
            },
        ),
    ]
