# Generated by Django 5.2.6 on 2026-06-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0030_resource_object_size_tenantvideoquota'),
    ]

    operations = [
        migrations.AddField(
            model_name='minioconfig',
            name='allow_video_cloud_url',
            field=models.BooleanField(default=True, verbose_name='Allow video cloud URL'),
        ),
    ]
