# Generated by Django 5.2.6 on 2026-07-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0040_controlcommandrecognitionpolicy_fixed_execution_reply'),
        ('tenants', '0004_membership_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='content_hash',
            field=models.CharField(blank=True, default='', editable=False, max_length=64, verbose_name='内容 SHA-256'),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.UniqueConstraint(condition=models.Q(('resource_type', 'image'), models.Q(('content_hash', ''), _negated=True)), fields=('tenant', 'content_hash'), name='unique_image_content_hash_per_tenant'),
        ),
    ]
