# Generated by Django 5.2.6 on 2026-05-31 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0005_chat_summary_message_feedback'),
        ('tenants', '0002_default_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversation',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='llmprovider',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='所属公司'),
        ),
    ]
