# Generated by Django 5.2.6 on 2026-06-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0007_asr_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asrconfig',
            options={'verbose_name': 'ASR 閰嶇疆', 'verbose_name_plural': 'ASR 閰嶇疆'},
        ),
        migrations.AlterField(
            model_name='asrconfig',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='鏄\ue21a惁鍚\ue21c敤'),
        ),
        migrations.AlterField(
            model_name='asrconfig',
            name='model',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='妯″瀷鍚嶇О'),
        ),
        migrations.AlterField(
            model_name='asrconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='鏇存柊鏃堕棿'),
        ),
    ]
