# Generated by Django 5.2.6 on 2026-06-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0007_asr_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asrconfig',
            options={'verbose_name': 'ASR 配置', 'verbose_name_plural': 'ASR 配置'},
        ),
        migrations.AlterField(
            model_name='asrconfig',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='asrconfig',
            name='model',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='模型名称'),
        ),
        migrations.AlterField(
            model_name='asrconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
