# Generated by Django 5.2.6 on 2026-06-06 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0009_asr_replacement_rule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asrreplacementrule',
            options={'ordering': ['id'], 'verbose_name': 'ASR 替换词', 'verbose_name_plural': 'ASR 替换词'},
        ),
        migrations.RemoveField(
            model_name='asrreplacementrule',
            name='sort_order',
        ),
    ]
