# Generated by Django 5.2.6 on 2026-06-09 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


AGENT_APPLICATION_PERMISSIONS = [
    ('查看应用管理', 'agent_applications.view', 'agent_applications', '允许查看智能体应用'),
    ('创建应用管理', 'agent_applications.create', 'agent_applications', '允许创建智能体应用'),
    ('编辑应用管理', 'agent_applications.update', 'agent_applications', '允许编辑智能体应用'),
    ('删除应用管理', 'agent_applications.delete', 'agent_applications', '允许删除智能体应用'),
]


def seed_agent_application_access_data(apps, schema_editor):
    Menu = apps.get_model('accounts', 'Menu')
    PermissionPoint = apps.get_model('accounts', 'PermissionPoint')
    Role = apps.get_model('accounts', 'Role')

    application_menu, _ = Menu.objects.update_or_create(
        key='/applications',
        defaults={
            'name': '应用管理',
            'path': '/applications',
            'icon': 'AppstoreOutlined',
            'audience': 'all',
            'sort_order': 20,
            'is_active': True,
            'parent_id': None,
        },
    )

    created_permissions = []
    for name, code, module, description in AGENT_APPLICATION_PERMISSIONS:
        permission, _ = PermissionPoint.objects.update_or_create(
            code=code,
            defaults={
                'name': name,
                'module': module,
                'description': description,
                'is_active': True,
            },
        )
        created_permissions.append(permission)

    editable_permissions = [
        permission
        for permission in created_permissions
        if permission.code in {'agent_applications.view', 'agent_applications.create', 'agent_applications.update'}
    ]
    for role in Role.objects.all():
        role.menus.add(application_menu)
        if role.code == 'admin':
            role.permission_points.add(*created_permissions)
        else:
            role.permission_points.add(*editable_permissions)


def unseed_agent_application_access_data(apps, schema_editor):
    Menu = apps.get_model('accounts', 'Menu')
    PermissionPoint = apps.get_model('accounts', 'PermissionPoint')

    PermissionPoint.objects.filter(code__startswith='agent_applications.').delete()
    Menu.objects.filter(key='/applications').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_seed_audit_logs_menu'),
        ('ai_models', '0010_remove_asr_replacement_sort_order'),
        ('knowledge_base', '0003_knowledgedocument_tenant'),
        ('tenants', '0004_membership_role_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='应用名称')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='应用说明')),
                ('model_name', models.CharField(blank=True, default='', max_length=128, verbose_name='模型名称')),
                ('system_prompt', models.TextField(blank=True, default='', verbose_name='系统提示词')),
                ('temperature', models.FloatField(default=0.7, verbose_name='Temperature')),
                ('max_tokens', models.PositiveIntegerField(default=1000, verbose_name='最大输出 Tokens')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agent_applications', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('knowledge_documents', models.ManyToManyField(blank=True, related_name='agent_applications', to='knowledge_base.knowledgedocument', verbose_name='绑定知识库文档')),
                ('llm_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_applications', to='ai_models.llmprovider', verbose_name='LLM 供应商')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '智能体应用',
                'verbose_name_plural': '智能体应用',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='ai_models.agentapplication', verbose_name='绑定应用'),
        ),
        migrations.AddConstraint(
            model_name='agentapplication',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_agent_application_name_per_tenant'),
        ),
        migrations.RunPython(seed_agent_application_access_data, unseed_agent_application_access_data),
    ]
