# Generated by Django 5.2.6 on 2026-06-09 17:34

import django.db.models.deletion
from django.db import migrations, models


def clear_old_llm_bindings(apps, schema_editor):
    ChatConversation = apps.get_model('ai_models', 'ChatConversation')
    AgentApplication = apps.get_model('ai_models', 'AgentApplication')
    for model in (ChatConversation, AgentApplication):
        update_kwargs = {}
        field_names = {field.name for field in model._meta.fields}
        if 'llm_provider' in field_names:
            update_kwargs['llm_provider'] = None
        if 'model_name' in field_names:
            update_kwargs['model_name'] = ''
        if 'llm_model' in field_names:
            update_kwargs['llm_model'] = None
        if update_kwargs:
            model.objects.all().update(**update_kwargs)


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0012_seed_agent_application_tenant_access'),
        ('tenants', '0004_membership_role_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMTestSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_prompt', models.TextField(default='请用一句中文回复：连接测试成功。', verbose_name='测试提示词')),
                ('test_cooldown_seconds', models.PositiveIntegerField(default=10, verbose_name='测速冷却秒数')),
                ('test_timeout_seconds', models.PositiveIntegerField(default=15, verbose_name='测速超时秒数')),
                ('test_max_tokens', models.PositiveIntegerField(default=64, verbose_name='测速最大输出 Tokens')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.RemoveField(
            model_name='llmprovider',
            name='models_config',
        ),
        migrations.RemoveField(
            model_name='llmprovider',
            name='tenant',
        ),
        migrations.AddField(
            model_name='llmprovider',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterModelOptions(
            name='llmprovider',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'LLM 供应商', 'verbose_name_plural': 'LLM 供应商'},
        ),
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='真实模型名称')),
                ('display_name', models.CharField(blank=True, default='', max_length=128, verbose_name='展示名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='ai_models.llmprovider', verbose_name='所属供应商')),
            ],
        ),
        migrations.AddField(
            model_name='agentapplication',
            name='llm_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_applications', to='ai_models.llmmodel', verbose_name='LLM 模型'),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='llm_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='ai_models.llmmodel', verbose_name='LLM 模型'),
        ),
        migrations.RunPython(clear_old_llm_bindings, migrations.RunPython.noop),
        migrations.CreateModel(
            name='TenantLLMModelGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_grants', to='ai_models.llmmodel', verbose_name='授权模型')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_model_grants', to='tenants.tenant', verbose_name='所属公司')),
            ],
        ),
        migrations.CreateModel(
            name='TenantLLMSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('default_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_default_settings', to='ai_models.llmmodel', verbose_name='默认模型')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llm_settings', to='tenants.tenant', verbose_name='所属公司')),
            ],
        ),
        migrations.AddConstraint(
            model_name='llmmodel',
            constraint=models.UniqueConstraint(fields=('provider', 'name'), name='uniq_llm_model_provider_name'),
        ),
        migrations.AddConstraint(
            model_name='tenantllmmodelgrant',
            constraint=models.UniqueConstraint(fields=('tenant', 'model'), name='uniq_tenant_llm_model_grant'),
        ),
    ]
