# Generated by Django 5.2.6 on 2026-06-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0023_llmmodel_enable_web_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='aliyun', max_length=32, unique=True, verbose_name='模型编码')),
                ('name', models.CharField(default='阿里云文本嵌入', max_length=128, verbose_name='模型名称')),
                ('api_key', models.CharField(blank=True, default='', max_length=512, verbose_name='API Key')),
                ('base_url', models.CharField(blank=True, default='https://dashscope.aliyuncs.com/compatible-mode/v1/embeddings', max_length=512, verbose_name='接口地址')),
                ('model', models.CharField(blank=True, default='text-embedding-v4', max_length=128, verbose_name='DashScope 模型')),
                ('dimensions', models.PositiveIntegerField(default=0, verbose_name='向量维度（0 表示模型默认）')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '嵌入模型',
                'verbose_name_plural': '嵌入模型',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RerankModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='aliyun', max_length=32, unique=True, verbose_name='模型编码')),
                ('name', models.CharField(default='阿里云文本重排序', max_length=128, verbose_name='模型名称')),
                ('api_key', models.CharField(blank=True, default='', max_length=512, verbose_name='API Key')),
                ('base_url', models.CharField(blank=True, default='https://dashscope.aliyuncs.com/api/v1/services/rerank/text-rerank/text-rerank', max_length=512, verbose_name='接口地址')),
                ('model', models.CharField(blank=True, default='qwen3-vl-rerank', max_length=128, verbose_name='DashScope 模型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '重排序模型',
                'verbose_name_plural': '重排序模型',
                'ordering': ['id'],
            },
        ),
    ]
