# Generated by Codex on 2026-07-02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0032_third_party_chatbots'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyChatbotIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_type', models.CharField(choices=[('scheme_a', '方案A')], default='scheme_a', max_length=32, verbose_name='方案类型')),
                ('name', models.CharField(max_length=128, verbose_name='方案实例名称')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='API 流程配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('chatbot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integration', to='ai_models.thirdpartychatbotapplication', verbose_name='第三方机器人')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='ai_models.thirdpartychatbotprovider', verbose_name='第三方供应商')),
            ],
            options={
                'verbose_name': '第三方会话机器人方案实例',
                'verbose_name_plural': '第三方会话机器人方案实例',
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
