# Generated by Codex on 2026-07-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0033_third_party_chatbot_integration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdpartychatbotprovider',
            name='provider_type',
            field=models.CharField(
                choices=[
                    ('configured_api_chatbot', '配置化 API 机器人'),
                    ('ihuapeng_chatbot', '华鹏会话机器人'),
                ],
                default='configured_api_chatbot',
                max_length=64,
                verbose_name='供应商类型',
            ),
        ),
        migrations.AlterField(
            model_name='thirdpartychatbotintegration',
            name='scheme_type',
            field=models.CharField(
                choices=[('scheme_a', '方案A'), ('scheme_b', '方案B')],
                default='scheme_a',
                max_length=32,
                verbose_name='方案类型',
            ),
        ),
    ]
