# Generated by Django 5.2.6 on 2026-07-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0038_bailian_managed_knowledge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bailianknowledgeconfig',
            name='category_id',
        ),
        migrations.AddField(
            model_name='tenantknowledgemodelsettings',
            name='bailian_category_error',
            field=models.TextField(blank=True, default='', verbose_name='Category 自动创建错误'),
        ),
        migrations.AddField(
            model_name='tenantknowledgemodelsettings',
            name='bailian_category_id',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='百炼租户 Category ID'),
        ),
        migrations.AddField(
            model_name='tenantknowledgemodelsettings',
            name='bailian_category_workspace_id',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Category 所属 Workspace ID'),
        ),
    ]
