# Generated by Django 5.2.6 on 2026-07-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0040_agent_follow_up_suggested_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='knowledge_references',
            field=models.JSONField(blank=True, default=list, verbose_name='知识引用快照'),
        ),
    ]
