# Generated by Django 5.2.6 on 2026-07-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0041_chatmessage_knowledge_references_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdpartychatbotprovider',
            name='provider_type',
            field=models.CharField(choices=[('configured_api_chatbot', '配置化 API 机器人'), ('ihuapeng_chatbot', '华鹏会话机器人')], default='ihuapeng_chatbot', max_length=64, verbose_name='供应商类型'),
        ),
    ]
