# Generated by Django 5.2.6 on 2026-07-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0042_alter_thirdpartychatbotprovider_provider_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CosyVoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key_encrypted', models.CharField(blank=True, default='', max_length=1024, verbose_name='加密 API Key')),
                ('websocket_url', models.CharField(blank=True, default='', max_length=512, verbose_name='WebSocket URL')),
                ('customization_url', models.CharField(blank=True, default='', max_length=512, verbose_name='音色定制 API URL')),
                ('default_test_text', models.TextField(default='对吧~我就特别喜欢这种超市，尤其是过年的时候去逛超市就会觉得超级超级开心！想买好多好多的东西呢！', verbose_name='默认测试文本')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('default_voice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ai_models.ttsvoice', verbose_name='默认音色')),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cosyvoice_settings', to='ai_models.ttsprovider', verbose_name='CosyVoice 供应商')),
            ],
            options={
                'verbose_name': 'CosyVoice 设置',
                'verbose_name_plural': 'CosyVoice 设置',
            },
        ),
        migrations.CreateModel(
            name='CosyVoiceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('enroll', '音色复刻'), ('design', '音色设计')], max_length=16, verbose_name='创建方式')),
                ('source_audio_url', models.URLField(blank=True, default='', max_length=512, verbose_name='源音频 URL')),
                ('description', models.TextField(blank=True, default='', verbose_name='设计描述')),
                ('language', models.CharField(blank=True, default='', max_length=32, verbose_name='语言')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('voice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cosyvoice_profile', to='ai_models.ttsvoice', verbose_name='CosyVoice 音色')),
            ],
            options={
                'verbose_name': 'CosyVoice 音色配置',
                'verbose_name_plural': 'CosyVoice 音色配置',
            },
        ),
    ]
