# Generated by Django 5.2.6 on 2026-07-29 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0043_cosyvoice_settings'),
        ('tenants', '0004_membership_role_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantTTSProviderGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('public_config', models.JSONField(blank=True, default=dict, verbose_name='公司卡片公共配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_grants', to='ai_models.ttsprovider', verbose_name='授权 TTS 卡片')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tts_provider_grants', to='tenants.tenant', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '公司 TTS 卡片授权',
                'verbose_name_plural': '公司 TTS 卡片授权',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'provider'), name='uniq_tenant_tts_provider_grant')],
            },
        ),
    ]
