# Generated by Django 5.1.7 on 2026-07-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0045_seed_tenant_tts_provider_grants'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmprovider',
            name='api_protocol',
            field=models.CharField(
                choices=[
                    ('chat_completions', 'OpenAI Chat Completions'),
                    ('responses', 'OpenAI Responses API'),
                ],
                default='chat_completions',
                max_length=32,
                verbose_name='API 协议',
            ),
        ),
    ]
