# Generated by Django 5.2.6 on 2026-08-03 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Voice-level TTS authorization: card grant mode + per-voice grants.

    Split from the ``owner_tenant`` column (0050) and the ``is_visible`` label
    change (0051) so each piece can be rolled back on its own.
    """

    dependencies = [
        ('ai_models', '0048_remove_legacy_loong_tts_voices'),
        ('tenants', '0004_membership_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantttsprovidergrant',
            name='grant_mode',
            field=models.CharField(choices=[('all', '全部音色'), ('selected', '指定音色')], default='all', help_text='全部音色：卡下所有上架音色自动可用；指定音色：仅勾选的音色可用。', max_length=16, verbose_name='授权范围'),
        ),
        migrations.CreateModel(
            name='TenantTTSVoiceGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tts_voice_grants', to='tenants.tenant', verbose_name='所属公司')),
                ('voice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_grants', to='ai_models.ttsvoice', verbose_name='授权音色')),
            ],
            options={
                'verbose_name': '公司 TTS 音色授权',
                'verbose_name_plural': '公司 TTS 音色授权',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'voice'), name='uniq_tenant_tts_voice_grant')],
            },
        ),
    ]
