# Generated by Django 5.2.6 on 2026-08-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0052_agentapplication_enable_web_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentapplication',
            name='tts_filter_punctuation',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='TTS 过滤标点'),
        ),
    ]
